# Generated by Django 4.2.5 on 2023-09-19 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='postsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('post_shortname', models.SlugField(max_length=255, unique=True)),
                ('post_published_date_time', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ImageField(blank=True, upload_to='posts/images')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
