# Generated by Django 4.2.5 on 2023-10-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewofpost', to='posts.postsm'),
        ),
    ]
